"""Enginuity core: canonical model schemas and provenance utilities."""

from .model import (
    SCHEMA_VERSION,
    ArcEntity,
    BBox,
    CircleEntity,
    ConstantForcing,
    DrawingModel,
    DrawingSource,
    Entity,
    Forcing,
    Layer,
    LineEntity,
    Point2,
    Poisson1DModel,
    Poisson1DResult,
    PolylineEntity,
    PolynomialForcing,
    SineForcing,
    Units,
)
from .methods import (
    Attempt,
    Budget,
    ErrorBasis,
    ErrorEstimate,
    Fidelity,
    MethodInfo,
    SelectionRecord,
)
from .provenance import (
    RunManifest,
    build_manifest,
    canonical_json,
    sha256_of_bytes,
    sha256_of_model,
)

__all__ = [
    "SCHEMA_VERSION",
    "Attempt",
    "Budget",
    "ErrorBasis",
    "ErrorEstimate",
    "Fidelity",
    "MethodInfo",
    "SelectionRecord",
    "ArcEntity",
    "BBox",
    "CircleEntity",
    "ConstantForcing",
    "DrawingModel",
    "DrawingSource",
    "Entity",
    "Forcing",
    "Layer",
    "LineEntity",
    "Point2",
    "Poisson1DModel",
    "Poisson1DResult",
    "PolylineEntity",
    "PolynomialForcing",
    "SineForcing",
    "Units",
    "RunManifest",
    "build_manifest",
    "canonical_json",
    "sha256_of_bytes",
    "sha256_of_model",
]
