
FROM python:3.13

WORKDIR /new

COPY /requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
#uvicorn main:app --reload --port 8000 (how I run it locally)
CMD ["uvicorn", "main:app", "--reload", "--port", "8000", "--host", "0.0.0.0"]